name: Build Firmware (PlatformIO)

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Cache pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          
    - name: Cache PlatformIO
      uses: actions/cache@v3
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
        
    - name: Build firmware
      run: |
        cd Build
        pio run
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: firmware-binaries
        path: |
          Build/.pio/build/esp32-c3-supermini/firmware.bin
          Build/.pio/build/esp32-c3-supermini/firmware.elf
          Build/.pio/build/esp32-c3-supermini/partitions.bin
          Build/.pio/build/esp32-c3-supermini/bootloader.bin
        retention-days: 30
        
    - name: Create release on tag
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          Build/.pio/build/esp32-c3-supermini/firmware.bin
          Build/.pio/build/esp32-c3-supermini/firmware.elf
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
