name: Build Firmware (ESP-IDF)

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'Build/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'Build/**'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        
    - name: Setup ESP-IDF
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v5.1.2
        target: esp32c3
        path: 'Build'
        
    - name: Build firmware
      run: |
        cd Build
        idf.py set-target esp32c3
        idf.py build
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: esp-idf-firmware
        path: |
          Build/build/bt_headset_module.bin
          Build/build/bt_headset_module.elf
          Build/build/bootloader/bootloader.bin
          Build/build/partition_table/partition-table.bin
        retention-days: 30
        
    - name: Create release on tag
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          Build/build/bt_headset_module.bin
          Build/build/bt_headset_module.elf
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
