name: Manual Build

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Build type'
        required: true
        default: 'platformio'
        type: choice
        options:
          - platformio
          - esp-idf
          - both
      debug_level:
        description: 'Debug level (0-5)'
        required: false
        default: '3'
        type: string
      create_release:
        description: 'Create release artifacts'
        required: false
        default: false
        type: boolean

jobs:
  build-platformio:
    if: ${{ inputs.build_type == 'platformio' || inputs.build_type == 'both' }}
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
        
    - name: Build firmware (PlatformIO)
      run: |
        cd Build
        # Update debug level if specified
        if [ "${{ inputs.debug_level }}" != "3" ]; then
          sed -i 's/CORE_DEBUG_LEVEL=3/CORE_DEBUG_LEVEL=${{ inputs.debug_level }}/' platformio.ini
        fi
        pio run
        
    - name: Upload PlatformIO artifacts
      uses: actions/upload-artifact@v3
      with:
        name: platformio-firmware
        path: |
          Build/.pio/build/esp32-c3-supermini/firmware.bin
          Build/.pio/build/esp32-c3-supermini/firmware.elf
          Build/.pio/build/esp32-c3-supermini/partitions.bin
          Build/.pio/build/esp32-c3-supermini/bootloader.bin
        retention-days: 7

  build-esp-idf:
    if: ${{ inputs.build_type == 'esp-idf' || inputs.build_type == 'both' }}
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        
    - name: Setup ESP-IDF
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v5.1.2
        target: esp32c3
        path: 'Build'
        
    - name: Build firmware (ESP-IDF)
      run: |
        cd Build
        idf.py set-target esp32c3
        idf.py build
        
    - name: Upload ESP-IDF artifacts
      uses: actions/upload-artifact@v3
      with:
        name: esp-idf-firmware
        path: |
          Build/build/bt_headset_module.bin
          Build/build/bt_headset_module.elf
          Build/build/bootloader/bootloader.bin
          Build/build/partition_table/partition-table.bin
        retention-days: 7

  create-release-package:
    if: ${{ inputs.create_release == true }}
    needs: [build-platformio]
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Download PlatformIO artifacts
      uses: actions/download-artifact@v3
      with:
        name: platformio-firmware
        path: firmware/
        
    - name: Create release package
      run: |
        mkdir -p release
        cp firmware/firmware.bin release/ATH-R50x-firmware-manual-build.bin
        cp firmware/firmware.elf release/ATH-R50x-firmware-manual-build.elf
        cp firmware/partitions.bin release/partitions.bin
        cp firmware/bootloader.bin release/bootloader.bin
        
        # Create flash script
        cat > release/flash.bat << 'EOF'
        @echo off
        echo Flashing ATH-R50x Bluetooth Headset Firmware (Manual Build)
        echo ========================================================
        echo.
        echo Make sure your ESP32-C3 is connected via USB-C
        echo Press any key to continue...
        pause >nul
        
        esptool.py --chip esp32c3 --port COM3 --baud 921600 write_flash ^
          0x0000 bootloader.bin ^
          0x8000 partitions.bin ^
          0x10000 ATH-R50x-firmware-manual-build.bin
        
        echo.
        echo Firmware flashed successfully!
        pause
        EOF
        
    - name: Upload release package
      uses: actions/upload-artifact@v3
      with:
        name: release-package
        path: release/
        retention-days: 30
