# Simple GitHub Actions Workflow for ESP32-C3 Bluetooth Headset

name: Build Firmware

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Cache PlatformIO
      uses: actions/cache@v4
      with:
        path: |
          ~/.platformio
          .pio
        key: ${{ runner.os }}-pio-${{ hashFiles('**/platformio.ini') }}
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
    
    - name: Build firmware
      run: |
        echo "Building firmware..."
        pio run -e esp32-c3-supermini --verbose
        
    - name: Prepare firmware for download
      run: |
        mkdir -p firmware
        cp .pio/build/esp32-c3-supermini/firmware.bin firmware/esp32-c3-bluetooth-headset.bin
        cp flash_firmware.bat firmware/
        cp flash_firmware.ps1 firmware/
        echo "Firmware built on: $(date)" > firmware/build_info.txt
        echo "Git commit: ${{ github.sha }}" >> firmware/build_info.txt
        
    - name: Upload firmware
      uses: actions/upload-artifact@v4
      with:
        name: esp32-c3-bluetooth-headset-firmware
        path: firmware/
        retention-days: 30

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Download firmware
      uses: actions/download-artifact@v4
      with:
        name: esp32-c3-bluetooth-headset-firmware
        path: ./firmware
        
    - name: Create release package
      run: |
        cd firmware
        zip -r ../esp32-c3-bluetooth-headset-${{ github.ref_name }}.zip .
        cd ..
    
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          esp32-c3-bluetooth-headset-${{ github.ref_name }}.zip
        draft: false
        prerelease: false
        generate_release_notes: true
        body: |
          ## ESP32-C3 Bluetooth Headset Firmware ${{ github.ref_name }}
          
          ### 📥 Download and Flash (Windows)
          
          1. **Download** the zip file below
          2. **Extract** all files to a folder
          3. **Run** `flash_firmware.bat` (or `flash_firmware.ps1` for PowerShell)
          4. **Follow** the on-screen instructions
          
          ### 🔧 Manual Flash
          
          If you prefer to flash manually:
          ```cmd
          esptool.py --chip esp32c3 --port COM3 write_flash 0x0000 esp32-c3-bluetooth-headset.bin
          ```
          
          ### 📋 What's Included
          
          - `esp32-c3-bluetooth-headset.bin` - Firmware binary
          - `flash_firmware.bat` - Windows batch script
          - `flash_firmware.ps1` - PowerShell script
          - `build_info.txt` - Build information
          
          ### 🎧 Hardware Setup
          
          Connect your ESP32-C3 SuperMini with:
          - QCC5124 codec, SSD1306 OLED, buttons as per documentation
          - Put in download mode: Hold BOOT + press RESET, then release BOOT
          - Connect to USB and run the flash script
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
