# GitHub Actions Workflow for ESP32-C3 Bluetooth Headset

name: PlatformIO CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        board: [esp32-c3-devkitm-1]
        
    steps:
    - uses: actions/checkout@v3
    
    - name: Cache pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Cache PlatformIO
      uses: actions/cache@v3
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
    
    - name: Build firmware
      run: pio run -e esp32-c3-supermini
    
    - name: Run tests
      run: pio test -e esp32-c3-supermini --verbose
    
    - name: Check code style
      run: |
        find src/ -name "*.cpp" -o -name "*.h" | xargs clang-format --dry-run --Werror
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: firmware-${{ matrix.board }}
        path: .pio/build/*/firmware.bin
        
  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        name: firmware-esp32-c3-devkitm-1
        path: ./release
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: ./release/*
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
